version: "3.9"

services:
  mysql:
    build: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  redis:
    build: redis
    ports:
      - "6379:6379"
  nginx:
    build: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/vhosts:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /mnt/code:/var/www/html
    #command: [nginx-debug, '-g', 'daemon off;'] # 使用debug模式
    privileged: true # 特权模式，解决挂载代码导致的权限问题
  php56:
    build: php56
    volumes:
      - /mnt/code/sdkhw.eyugame.com:/var/www/html
  laravel56:
    build: php56
    volumes:
      - /mnt/code/laravel56:/var/www/html
  php74:
    build: php74
    volumes:
      - /mnt/code/sdkhw-x.eyugame.com:/var/www/html
    privileged: true
    environment:
      - APP_ENV=production
#  postgresql:
#    image: postgres:14.5
#    environment:
#      - POSTGRES_PASSWORD=111111
#      - POSTGRES_USER=root
#    privileged: true
#    volumes:
#      - ./postgresql/data:/var/lib/postgresql/data
#  svn-edge:
#    image: svnedge/app:latest
#    ports:
#      - "18080:18080"
#      - "3343:3343"
#    environment:
#      SET_PERMS: "false"
#    volumes:
#      - /tmp/svnedge/csvn/data:/home/svnedge/csvn/data
#  busybox:
#    build: ./busybox