apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
caCertPath: /etc/kubernetes/pki/ca.crt
discovery:
  bootstrapToken:
    apiServerEndpoint: kube-apiserver:6443
    token: abcdef.0123456789abcdef
    unsafeSkipCAVerification: true
  timeout: 5m0s
  tlsBootstrapToken: abcdef.0123456789abcdef
nodeRegistration:
  criSocket: unix:///var/run/cri-dockerd.sock
  imagePullPolicy: IfNotPresent
  name: debian
  taints: null
# kubeadm join 192.168.6.168:6443 --token abcdef.0123456789abcdef \
#        --discovery-token-ca-cert-hash sha256:0f5cb801e47761f965cafbca03d6617cf64dd2e085da44776cf2d30af8577acb